import os
import sys
import requests
import json
import google.generativeai as genai
from datetime import datetime

print("=== BOSS EMPIRE SCANNER ACTIVATED ===")

# --- 1. Configuration ---
genai.configure(api_key=os.environ['GOOGLE_API_KEY'])

# List available models to debug (only once)
print("[*] Checking available Gemini models...")
try:
    available_models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
    print(f"[*] Available: {available_models}")
except Exception as e:
    print(f"[!] Could not list models: {e}")

# Use a known working free model
# Options: 'models/gemini-2.0-flash', 'models/gemini-2.0-flash-lite', 'models/gemini-1.5-flash' (deprecated)
MODEL_NAME = 'models/gemini-2.0-flash'
print(f"[*] Using model: {MODEL_NAME}")

try:
    model = genai.GenerativeModel(MODEL_NAME)
except Exception as e:
    print(f"[!] Failed to initialize model: {e}")
    sys.exit(1)

RAPIDAPI_KEY = os.environ['RAPIDAPI_KEY']
RAPIDAPI_HOST = os.environ['RAPIDAPI_HOST']
GUMROAD_ACCESS_TOKEN = os.environ.get('GUMROAD_ACCESS_TOKEN', '')

# --- 2. Data Fetch (Fallback to Simulated) ---
def fetch_reddit_prompts():
    print("[*] Attempting to fetch Reddit prompts...")
    # We'll use fallback for now to ensure the pipeline works
    # Once everything is stable, we can fix RapidAPI integration
    return get_fallback_prompts()

def get_fallback_prompts():
    print("[*] Using fallback prompt dataset (real scraping to be enabled after stable).")
    return [
        "I need a 30-day email sequence for a 'Seniors Fitness Tracker' app.",
        "Generate 50 catchy names for a 'Purple Dog Shampoo' brand.",
        "Script to automatically fix 'CapCut Blurry Export' on iPhone 16.",
        "Best niche for a new YouTube channel in 2026 without showing face.",
        "Cold DM template for real estate agents offering AI video editing.",
    ]

# --- 3. AI Analysis ---
def analyze_prompts(prompts):
    print("[*] AI analyzing market gaps...")
    prompt_text = "\n".join(prompts)
    instruction = """
    You are a business intelligence analyst. Review the following raw AI prompts from users.
    Identify the ONE niche where people are actively trying to build a solution, but there is a clear gap in the market for a specific tool or service to connect them to customers.
    Format your answer EXACTLY like this (3 parts separated by colons):
    [Niche Name] : [The Identified Gap] : [Proposed Shovel Idea]
    
    Example:
    [CapCut Video Editors] : [Frustration with export settings on iPhone 16] : [A one-click preset converter tool]
    """
    try:
        response = model.generate_content([instruction, prompt_text])
        return response.text.strip()
    except Exception as e:
        print(f"[!] AI analysis failed: {e}")
        return "[General AI Users] : [Lack of specific, actionable niche tools] : [Micro-SaaS solutions]"

# --- 4. Create Report Text ---
def create_report(analysis):
    date_str = datetime.now().strftime("%Y-%m-%d")
    report_content = f"""
SHADOW ECONOMY REPORT - {date_str}
============================================
Generated by The Boss's AI Swarm.

RAW INTEL ANALYSIS:
{analysis}

RECOMMENDED ACTION:
Build a simple tool or guide addressing the gap above. 
Offer it as a lead magnet for the "Shovel Idea" market.
"""
    filename = f"report_{date_str}.txt"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report_content)
    print(f"[+] Report saved locally as {filename}")
    return filename, report_content, analysis

# --- 5. Main Execution ---
def main():
    prompts = fetch_reddit_prompts()
    if not prompts:
        print("[!] No prompts found. Exiting.")
        return
    
    analysis = analyze_prompts(prompts)
    print(f"[+] Analysis: {analysis}")
    
    filename, report_content, _ = create_report(analysis)
    
    # Skip Gumroad for now; we'll add after stable
    print("\n=== MISSION COMPLETE. BOSS OUT. ===")

if __name__ == "__main__":
    main()
