import os
import sys
import requests
import json
import google.generativeai as genai
from datetime import datetime

print("=== BOSS EMPIRE SCANNER ACTIVATED ===")

# --- 1. Configuration ---
genai.configure(api_key=os.environ['GOOGLE_API_KEY'])

# List available models to debug (only once)
print("[*] Checking available Gemini models...")
try:
    available_models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
    print(f"[*] Available: {available_models}")
except Exception as e:
    print(f"[!] Could not list models: {e}")

# Use a known working free model
# Options: 'models/gemini-2.0-flash', 'models/gemini-2.0-flash-lite', 'models/gemini-1.5-flash' (deprecated)
MODEL_NAME = 'models/gemini-2.0-flash'
print(f"[*] Using model: {MODEL_NAME}")

try:
    model = genai.GenerativeModel(MODEL_NAME)
except Exception as e:
    print(f"[!] Failed to initialize model: {e}")
    sys.exit(1)

RAPIDAPI_KEY = os.environ['RAPIDAPI_KEY']
RAPIDAPI_HOST = os.environ['RAPIDAPI_HOST']
GUMROAD_ACCESS_TOKEN = os.environ.get('GUMROAD_ACCESS_TOKEN', '')

# --- 2. Data Fetch (Fallback to Simulated) ---
def fetch_reddit_prompts():
    print("[*] Scanning Reddit for AI prompt discussions...")
    
    url = "https://reddit-scraper2.p.rapidapi.com/search_posts_v2"
    querystring = {
        "query": "AI prompt help OR ChatGPT prompt",
        "sort": "NEW",
        "limit": "20"
    }
    headers = {
        "X-RapidAPI-Key": RAPIDAPI_KEY,
        "X-RapidAPI-Host": RAPIDAPI_HOST
    }
    
    try:
        response = requests.get(url, headers=headers, params=querystring, timeout=15)
        if response.status_code == 200:
            data = response.json()
            posts = data.get('data', []) or data.get('posts', [])
            prompts = []
            for post in posts[:15]:
                title = post.get('title', '')
                body = post.get('description', '') or post.get('body', '') or ''
                combined = f"{title}. {body}"[:500]
                if len(combined) > 20:
                    prompts.append(combined)
            if prompts:
                print(f"[+] Captured {len(prompts)} real Reddit prompts.")
                return prompts
        print("[!] Reddit scrape failed, using fallback.")
        return get_fallback_prompts()
    except Exception as e:
        print(f"[!] Reddit error: {e}. Using fallback.")
        return get_fallback_prompts()

def get_fallback_prompts():
    print("[*] Using fallback prompt dataset (real scraping to be enabled after stable).")
    return [
        "I need a 30-day email sequence for a 'Seniors Fitness Tracker' app.",
        "Generate 50 catchy names for a 'Purple Dog Shampoo' brand.",
        "Script to automatically fix 'CapCut Blurry Export' on iPhone 16.",
        "Best niche for a new YouTube channel in 2026 without showing face.",
        "Cold DM template for real estate agents offering AI video editing.",
    ]

# --- 3. AI Analysis ---
def analyze_prompts(prompts):
    print("[*] AI analyzing market gaps...")
    prompt_text = "\n".join(prompts)
    instruction = """
    You are a business intelligence analyst. Review the following raw AI prompts from users.
    Identify the ONE niche where people are actively trying to build a solution, but there is a clear gap in the market for a specific tool or service to connect them to customers.
    Format your answer EXACTLY like this (3 parts separated by colons):
    [Niche Name] : [The Identified Gap] : [Proposed Shovel Idea]
    
    Example:
    [CapCut Video Editors] : [Frustration with export settings on iPhone 16] : [A one-click preset converter tool]
    """
    try:
        response = model.generate_content([instruction, prompt_text])
        return response.text.strip()
    except Exception as e:
        print(f"[!] AI analysis failed: {e}")
        return "[General AI Users] : [Lack of specific, actionable niche tools] : [Micro-SaaS solutions]"

# --- 4. Create Report Text ---
def create_report(analysis):
    date_str = datetime.now().strftime("%Y-%m-%d")
    report_content = f"""
SHADOW ECONOMY REPORT - {date_str}
============================================
Generated by The Boss's AI Swarm.

RAW INTEL ANALYSIS:
{analysis}

RECOMMENDED ACTION:
Build a simple tool or guide addressing the gap above. 
Offer it as a lead magnet for the "Shovel Idea" market.
"""
    filename = f"report_{date_str}.txt"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report_content)
    print(f"[+] Report saved locally as {filename}")
    return filename, report_content, analysis
def create_gumroad_product(report_content, analysis):
    print("[*] Publishing to Gumroad...")
    
    parts = analysis.split(':')
    if len(parts) >= 3:
        niche = parts[0].strip().strip('[]')
    else:
        niche = "Market Gap"
    
    date_str = datetime.now().strftime("%b %d, %Y")
    product_title = f"Shadow Economy Report: {niche} - {date_str}"
    
    url = "https://api.gumroad.com/v2/products"
    headers = {
        "Authorization": f"Bearer {GUMROAD_ACCESS_TOKEN}",
        "Content-Type": "application/json"
    }
    payload = {
        "name": product_title,
        "description": report_content,
        "price": 4900,  # $49.00 in cents
        "max_purchase_count": 50,
        "custom_permalink": f"shadow-report-{datetime.now().strftime('%Y%m%d%H%M')}",
        "published": True
    }
    
    try:
        response = requests.post(url, headers=headers, json=payload, timeout=15)
        if response.status_code in [200, 201]:
            data = response.json()
            return data['product']['short_url']
        else:
            print(f"[!] Gumroad error: {response.status_code}")
            return None
    except Exception as e:
        print(f"[!] Gumroad exception: {e}")
        return None
# --- 5. Main Execution ---
def main():
    prompts = fetch_reddit_prompts()
    if not prompts:
        print("[!] No prompts found. Exiting.")
        return
    
    analysis = analyze_prompts(prompts)
    print(f"[+] Analysis: {analysis}")
    
    filename, report_content, _ = create_report(analysis)
    
    # Auto-publish to Gumroad if token exists
    if GUMROAD_ACCESS_TOKEN and len(GUMROAD_ACCESS_TOKEN) > 10:
        product_url = create_gumroad_product(report_content, analysis)
        if product_url:
            print(f"\n✅ PRODUCT LIVE: {product_url}")
            with open("latest_product_url.txt", "w") as f:
                f.write(product_url)
        else:
            print("\n⚠️ Gumroad publish failed. Check token.")
    else:
        print("\n⚠️ Gumroad token missing. Skipping publish.")
    
    print("\n=== MISSION COMPLETE. BOSS OUT. ===")
